export default {
    "pagination": {
        "limit": 5,
        "offset": 0,
        "count": 5,
        "total": 1255
    },
    "data": [
        {
            "open": 5.28,
            "high": 5.32,
            "low": 4.78,
            "close": 4.79,
            "volume": 11005600.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 4.79,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "GEVO",
            "exchange": "XNAS",
            "date": "2021-12-03T00:00:00+0000"
        },
        {
            "open": 164.02,
            "high": 164.96,
            "low": 159.72,
            "close": 161.84,
            "volume": 117938300.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 161.84,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "AAPL",
            "exchange": "XNAS",
            "date": "2021-12-03T00:00:00+0000"
        },
        {
            "open": 3.68,
            "high": 3.73,
            "low": 3.34,
            "close": 3.4,
            "volume": 14190700.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 3.4,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "BNGO",
            "exchange": "XNAS",
            "date": "2021-12-03T00:00:00+0000"
        },
        {
            "open": 49.68,
            "high": 50.06,
            "low": 48.76,
            "close": 49.25,
            "volume": 32221900.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 49.25,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "INTC",
            "exchange": "XNAS",
            "date": "2021-12-03T00:00:00+0000"
        },
        {
            "open": 17.27,
            "high": 17.29,
            "low": 16.34,
            "close": 16.62,
            "volume": 57791200.0,
            "adj_high": null,
            "adj_low": null,
            "adj_close": 16.62,
            "adj_open": null,
            "adj_volume": null,
            "split_factor": 1.0,
            "dividend": 0.0,
            "symbol": "AAL",
            "exchange": "XNAS",
            "date": "2021-12-03T00:00:00+0000"
        }
    ]
}
