export default [
    {
        "author": "Alexi Cohan",
        "title": "Massachusetts teachers to make push for early retirement bill during Wednesday hearing",
        "description": "Massachusetts teachers on Wednesday will be making the push before the Joint Committee on Public Service for an early retirement bill that would allow educators to purchase years of service or age and districts to usher in a set of new hires. ",
        "url": "https://www.bostonherald.com/2021/08/31/massachusetts-teachers-to-make-push-for-early-retirement-bill-during-wednesday-hearing/",
        "source": "bostonherald",
        "image": "https://www.bostonherald.com/wp-content/uploads/2020/09/borDay01.jpg?w=1400px&strip=all",
        "category": "general",
        "language": "en",
        "country": "us",
        "published_at": "2021-09-01T00:07:30+00:00"
    },
    {
        "author": "Jenna Ciccotelli",
        "title": "Red Sox’s Nick Yorke Cracks Baseball America’s Top 100 Prospect List",
        "description": "The Boston Red Sox got a good one in Nick Yorke, and the folks over at Baseball America have taken notice. Yorke on Tuesday cracked the publication&#8217;s list of the Top 100 prospects in baseball. He was one of two additions after a pair of players used up their prospect eligibility. He ranked No. 99 [&#8230;]The post Red Sox&#8217;s Nick Yorke Cracks Baseball America&#8217;s Top 100 Prospect List appeared first on NESN.com.",
        "url": "https://nesn.com/2021/08/red-sox-nick-yorke-cracks-baseball-america-top-100-prospect-list/",
        "source": "nesn",
        "image": "https://nesn.com/wp-content/uploads/sites/5/2021/08/nick-yorke-1.jpg",
        "category": "general",
        "language": "en",
        "country": "us",
        "published_at": "2021-09-01T00:06:47+00:00"
    },
    {
        "author": "ABMN Staff",
        "title": "Encompass Health Co. (NYSE:EHC) Stock Position Raised by Magnetar Financial LLC",
        "description": "Encompass Health Co. (NYSE:EHC) Stock Position Raised by Magnetar Financial LLC",
        "url": "https://www.americanbankingnews.com/2021/08/31/encompass-health-co-nyseehc-stock-position-raised-by-magnetar-financial-llc.html",
        "source": "americanbankingnews",
        "image": null,
        "category": "general",
        "language": "en",
        "country": "us",
        "published_at": "2021-09-01T00:06:45+00:00"
    },
    {
        "author": "ABMN Staff",
        "title": "Magnetar Financial LLC Increases Stake in Syneos Health, Inc. (NASDAQ:SYNH)",
        "description": "Magnetar Financial LLC Increases Stake in Syneos Health, Inc. (NASDAQ:SYNH)",
        "url": "https://www.americanbankingnews.com/2021/08/31/magnetar-financial-llc-increases-stake-in-syneos-health-inc-nasdaqsynh.html",
        "source": "americanbankingnews",
        "image": null,
        "category": "general",
        "language": "en",
        "country": "us",
        "published_at": "2021-09-01T00:06:43+00:00"
    },
    {
        "author": "ABMN Staff",
        "title": "Magnetar Financial LLC Has $23.89 Million Position in Revolution Healthcare Acquisition Corp. (NASDAQ:REVHU)",
        "description": "Magnetar Financial LLC Has $23.89 Million Position in Revolution Healthcare Acquisition Corp. (NASDAQ:REVHU)",
        "url": "https://www.americanbankingnews.com/2021/08/31/magnetar-financial-llc-has-23-89-million-position-in-revolution-healthcare-acquisition-corp-nasdaqrevhu.html",
        "source": "americanbankingnews",
        "image": null,
        "category": "general",
        "language": "en",
        "country": "us",
        "published_at": "2021-09-01T00:06:41+00:00"
    },
    {
        "author": "The Canadian Press",
        "title": "Criminal negligence charge stayed in 2009 worker death at Toba Inlet project in B.C. (BC)",
        "description": "A stay of proceedings has been entered in the case of two supervisors and a British Columbia engineering company facing one count each of criminal negligence in connection with a workplace death more than a decade ago. The B.C. Prosecution Service says in a statement it recently determined the avail...",
        "url": "https://www.castanet.net/news/BC/344445/Criminal-negligence-charge-stayed-in-2009-worker-death-at-Toba-Inlet-project-in-B-C",
        "source": "Castanet",
        "image": "https://www.castanet.net/content/2021/8/screen_shot_2017-10-30_at_10.20.10_am_p3260818_p3518833_p3549717.jpg",
        "category": "general",
        "language": "en",
        "country": "us",
        "published_at": "2021-09-01T00:07:00+00:00"
    },
    {
        "author": "BeauHD",
        "title": "Why the Solana Cryptocurrency Is Surging",
        "description": "An anonymous reader shares a report from Fast Company, written by Michael Grothaus: One of the biggest movers on the cryptocurrency market in the past 24 hours is Solana. As of the time of this writing, Solana is up almost 20% over the past day, according to Coinbase. In the past week, it's up over 58%, and in the past month, it's up 275%. As for the past year, Solana has surged over 2,348%. What is Solana? Solana is a decentralized blockchain platform. It facilitates the transactions of the SOL coin as well as digital assets like non-fungible tokens (NFTs). Is Solana a bitcoin competitor? Sure...",
        "url": "https://slashdot.org/story/21/08/31/2139251/why-the-solana-cryptocurrency-is-surging?utm_source=rss1.0mainlinkanon&utm_medium=feed",
        "source": "slashdot",
        "image": null,
        "category": "general",
        "language": "en",
        "country": "us",
        "published_at": "2021-09-01T00:02:00+00:00"
    },
    {
        "author": "Kerry Crowley",
        "title": "SF Giants’ Cueto returns from COVID-19 IL after one day, Longoria gets cortisone shot",
        "description": "SF Giants starter Johnny Cueto was scratched from his scheduled outing on Monday after feeling ill.",
        "url": "https://www.mercurynews.com/2021/08/31/sf-giants-cueto-returns-from-covid-19-il-after-one-day-longoria-gets-cortisone-shot/",
        "source": "Mercury News",
        "image": "https://www.mercurynews.com/wp-content/uploads/2021/07/BNG-L-GIANTS-0730-02.jpg?w=1400px&strip=all",
        "category": "general",
        "language": "en",
        "country": "us",
        "published_at": "2021-09-01T00:10:46+00:00"
    },
    {
        "author": "Kerry Crowley",
        "title": "SF Giants’ Cueto returns from COVID-19 IL after one day, Longoria gets cortisone shot",
        "description": "SF Giants starter Johnny Cueto was scratched from his scheduled outing on Monday after feeling ill.",
        "url": "https://www.thereporter.com/2021/08/31/sf-giants-cueto-returns-from-covid-19-il-after-one-day-longoria-gets-cortisone-shot/",
        "source": "thereporter",
        "image": "https://www.thereporter.com/wp-content/uploads/2021/08/BNG-L-GIANTS-0730-02.jpg?w=1400px&strip=all",
        "category": "general",
        "language": "en",
        "country": "us",
        "published_at": "2021-09-01T00:10:46+00:00"
    },
    {
        "author": "WWAY News",
        "title": "Nearly 1 in 5 Horry County Schools students in quarantine",
        "description": "HCS said students in quarantine can take their personal learning device home to receive and turn in assignments, plus log onto virtual school.",
        "url": "https://www.wwaytv3.com/2021/08/31/nearly-1-in-5-horry-county-schools-students-in-quarantine/",
        "source": "wwaytv3",
        "image": "https://www.wwaytv3.com/wp-content/uploads/2020/08/MGN_1280x960_00506B00-KDHIS-e1605541660698-1200x847.jpg",
        "category": "general",
        "language": "en",
        "country": "us",
        "published_at": "2021-09-01T00:05:01+00:00"
    },
    {
        "author": "Blaise Gainey",
        "title": "11 Bridges Damaged In Flood, Some Need Total Replacement",
        "description": "Three bridges in Humphreys County and one in Hickman were damaged beyond repair by flooding there this month. Replacing them will begin this fall and could take up to 12 months. The Aug. 21 storm caused a 1,000-year flood, resulting in millions in damages, destroying more than 250 homes and eroding the land around bridges. [&#8230;]",
        "url": "https://wpln.org/post/11-bridges-damaged-in-flood-some-need-total-replacement/",
        "source": "wpln",
        "image": null,
        "category": "general",
        "language": "en",
        "country": "us",
        "published_at": "2021-09-01T00:01:54+00:00"
    },
    {
        "author": "",
        "title": "China shutters American Chamber of Commerce in Chengdu",
        "description": "In July 2020, China closed the US consulate in Chengdu in retaliation for being ousted from its Houston consulate a week earlier.",
        "url": "https://www.smh.com.au/world/asia/china-shutters-american-chamber-of-commerce-in-chengdu-20210901-p58nri.html?ref=rss&utm_medium=rss&utm_source=rss_feed",
        "source": "The Sydney Morning Herald",
        "image": null,
        "category": "general",
        "language": "en",
        "country": "au",
        "published_at": "2021-09-01T00:03:08+00:00"
    },
    {
        "author": "Alyaa Stohy",
        "title": "Commodity Exchange to start operation in Q1 2022",
        "description": "Ibrahim Ashmawy, head of the Internal Trade Development Authority (ITDA), said that the government aims to launch the Egyptian Commodity Exchange in the first quarter (Q1) of next year.&#160; The Commodity Exchange has been established within the framework of the state’s plan to develop internal trade. He pointed out that trading in any commodity exchange &#8230;The post Commodity Exchange to start operation in Q1 2022 appeared first on Daily News Egypt.",
        "url": "https://dailynewsegypt.com/2021/09/01/commodity-exchange-to-start-operation-in-q1-2022/",
        "source": "thedailynewsegypt",
        "image": "http://dneegypt.nyc3.digitaloceanspaces.com/2021/09/hmawe-768x430.jpg",
        "category": "general",
        "language": "en",
        "country": "us",
        "published_at": "2021-09-01T00:31:40+00:00"
    },
    {
        "author": "The Conversation",
        "title": "The Taliban reportedly got US biometric devices — a lesson in life-and-death consequences of data privacy",
        "description": "by Margaret Hu, Penn StateIn the wake of the Taliban's takeover of Kabul and the ouster of the Afghan national government, alarming reports indicate that the insurgents could potentially access biometric data collected by the U.S. to track Afghans, including people who worked for U.S. and coalition forces. Afghans who once supported the U.S. have been attempting to hide or destroy physical and digital evidence of their identities. Many Afghans fear that the identity documents and databases storing personally identifiable data could be transformed into death warrants in the hands of the Taliban...",
        "url": "https://www.alternet.org/2021/09/talbian-biometric-data/",
        "source": "alternet",
        "image": "https://www.alternet.org/media-library/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbWFnZSI6Imh0dHBzOi8vYXNzZXRzLnJibC5tcy8yNzM2NzIxOS9vcmlnaW4uanBnIiwiZXhwaXJlc19hdCI6MTY3MTY4NjE0NH0.KdhdikoAVIxxCN-zk0PYVleoVymoS-AoJWiG20jlfOQ/image.jpg?width=980",
        "category": "general",
        "language": "en",
        "country": "us",
        "published_at": "2021-09-01T00:34:25+00:00"
    },
    {
        "author": "City News Service",
        "title": "USC study: California dispensaries lack adequate screening to keep out minors",
        "description": "The new study in JAMA Pediatrics evaluates how regulations designed to protect minors have held up five years after voters legalized cannabis.",
        "url": "https://www.sgvtribune.com/2021/08/31/usc-study-california-dispensaries-lack-adequate-screening-to-keep-out-minors/",
        "source": "sgvtribune",
        "image": "https://www.sgvtribune.com/wp-content/uploads/2021/08/Illegal-legal-weed-top-2.jpg?w=1400px&strip=all",
        "category": "general",
        "language": "en",
        "country": "us",
        "published_at": "2021-09-01T00:32:21+00:00"
    },
    {
        "author": "City News Service",
        "title": "USC study: California dispensaries lack adequate screening to keep out minors",
        "description": "The new study in JAMA Pediatrics evaluates how regulations designed to protect minors have held up five years after voters legalized cannabis.",
        "url": "https://www.presstelegram.com/2021/08/31/usc-study-california-dispensaries-lack-adequate-screening-to-keep-out-minors/",
        "source": "Press-Telegram",
        "image": "https://www.presstelegram.com/wp-content/uploads/2021/08/Illegal-legal-weed-top-1.jpg?w=1400px&strip=all",
        "category": "general",
        "language": "en",
        "country": "us",
        "published_at": "2021-09-01T00:32:21+00:00"
    },
    {
        "author": "ABMN Staff",
        "title": "Citadel (CTL) Price Tops $0.0061 on Exchanges",
        "description": "Citadel (CTL) Price Tops $0.0061 on Exchanges",
        "url": "https://www.americanbankingnews.com/2021/08/31/citadel-ctl-price-tops-0-0061-on-exchanges.html",
        "source": "americanbankingnews",
        "image": null,
        "category": "general",
        "language": "en",
        "country": "us",
        "published_at": "2021-09-01T00:30:47+00:00"
    },
    {
        "author": "ABMN Staff",
        "title": "Mining Core Coin (MCC) Price Up 10.2% Over Last Week",
        "description": "Mining Core Coin (MCC) Price Up 10.2% Over Last Week",
        "url": "https://www.americanbankingnews.com/2021/08/31/mining-core-coin-mcc-price-up-10-2-over-last-week.html",
        "source": "americanbankingnews",
        "image": null,
        "category": "general",
        "language": "en",
        "country": "us",
        "published_at": "2021-09-01T00:30:47+00:00"
    },
    {
        "author": "ABMN Staff",
        "title": "Smith Asset Management Group LP Sells 6,775 Shares of Rockwell Automation, Inc. (NYSE:ROK)",
        "description": "Smith Asset Management Group LP Sells 6,775 Shares of Rockwell Automation, Inc. (NYSE:ROK)",
        "url": "https://www.americanbankingnews.com/2021/08/31/smith-asset-management-group-lp-sells-6775-shares-of-rockwell-automation-inc-nyserok.html",
        "source": "americanbankingnews",
        "image": null,
        "category": "general",
        "language": "en",
        "country": "us",
        "published_at": "2021-09-01T00:30:47+00:00"
    },
    {
        "author": "ABMN Staff",
        "title": "ExNetwork Token (EXNT) Price Reaches $0.15 on Major Exchanges",
        "description": "ExNetwork Token (EXNT) Price Reaches $0.15 on Major Exchanges",
        "url": "https://www.americanbankingnews.com/2021/08/31/exnetwork-token-exnt-price-reaches-0-15-on-major-exchanges.html",
        "source": "americanbankingnews",
        "image": null,
        "category": "general",
        "language": "en",
        "country": "us",
        "published_at": "2021-09-01T00:30:47+00:00"
    },
    {
        "author": "ABMN Staff",
        "title": "Smith Asset Management Group LP Takes $12.69 Million Position in Carter&#8217;s, Inc. (NYSE:CRI)",
        "description": "Smith Asset Management Group LP Takes $12.69 Million Position in Carter&#8217;s, Inc. (NYSE:CRI)",
        "url": "https://www.americanbankingnews.com/2021/08/31/smith-asset-management-group-lp-takes-12-69-million-position-in-carters-inc-nysecri.html",
        "source": "americanbankingnews",
        "image": null,
        "category": "general",
        "language": "en",
        "country": "us",
        "published_at": "2021-09-01T00:30:46+00:00"
    },
    {
        "author": "ABMN Staff",
        "title": "DENTSPLY SIRONA Inc. (NASDAQ:XRAY) Holdings Raised by Smith Asset Management Group LP",
        "description": "DENTSPLY SIRONA Inc. (NASDAQ:XRAY) Holdings Raised by Smith Asset Management Group LP",
        "url": "https://www.americanbankingnews.com/2021/08/31/dentsply-sirona-inc-nasdaqxray-holdings-raised-by-smith-asset-management-group-lp.html",
        "source": "americanbankingnews",
        "image": null,
        "category": "general",
        "language": "en",
        "country": "us",
        "published_at": "2021-09-01T00:30:41+00:00"
    },
    {
        "author": "ABMN Staff",
        "title": "Smith Asset Management Group LP Makes New Investment in Everest Re Group, Ltd. (NYSE:RE)",
        "description": "Smith Asset Management Group LP Makes New Investment in Everest Re Group, Ltd. (NYSE:RE)",
        "url": "https://www.americanbankingnews.com/2021/08/31/smith-asset-management-group-lp-makes-new-investment-in-everest-re-group-ltd-nysere.html",
        "source": "americanbankingnews",
        "image": null,
        "category": "general",
        "language": "en",
        "country": "us",
        "published_at": "2021-09-01T00:30:41+00:00"
    },
    {
        "author": "ABMN Staff",
        "title": "Smith Asset Management Group LP Buys Shares of 103,107 IQVIA Holdings Inc. (NYSE:IQV)",
        "description": "Smith Asset Management Group LP Buys Shares of 103,107 IQVIA Holdings Inc. (NYSE:IQV)",
        "url": "https://www.americanbankingnews.com/2021/08/31/smith-asset-management-group-lp-buys-shares-of-103107-iqvia-holdings-inc-nyseiqv.html",
        "source": "americanbankingnews",
        "image": null,
        "category": "general",
        "language": "en",
        "country": "us",
        "published_at": "2021-09-01T00:30:41+00:00"
    },
    {
        "author": "ABMN Staff",
        "title": "SBank (STS) Reaches Market Capitalization of $85,472.18",
        "description": "SBank (STS) Reaches Market Capitalization of $85,472.18",
        "url": "https://www.americanbankingnews.com/2021/08/31/sbank-sts-reaches-market-capitalization-of-85472-18.html",
        "source": "americanbankingnews",
        "image": null,
        "category": "general",
        "language": "en",
        "country": "us",
        "published_at": "2021-09-01T00:28:47+00:00"
    }
]